### ISSUE TITLE
does not run

### ISSUE THREAD

**Issue by zwzhang123** [Simon4Yan/eSPGAN#7]
the training and testing codes of spgan exist two or more bugs.
1. https://github.com/Simon4Yan/eSPGAN/blob/master/py-spgan/train_spgan.py#L104
2. https://github.com/Simon4Yan/eSPGAN/blob/master/py-spgan/test_spgan.py#L58

**Comment by Simon4Yan** [comment]
Hi, thanks for your question.

There are not bugs. First, you could use zip instead of itertools.izip (maybe you are asking this, it depends on your python version); Second, please make sure your dataset size can be divided exactly by the [batch size ](https://github.com/Simon4Yan/eSPGAN/blob/1c591d378b71a24d51be063d0aae17e0bc8f22c6/py-spgan/test_spgan.py#L21).

Hope the above is helpful for you.

**Comment by zwzhang121** [comment]
thx.
https://github.com/Simon4Yan/eSPGAN/blob/master/py-spgan/train_spgan.py#L104
I have used zip instead of itertools.zip, since the size of a_loader, b_loader is different, so when i>12936，a_real will be empty.

**Comment by Simon4Yan** [comment]
No, you misunderstood the usage of zip. The zip() function will only iterate over the smallest list passed. If given lists of different lengths, the resulting combination will only be as long as the smallest list passed.

**Comment by zwzhang121** [comment]
thx. I got the errors as follows, I tried to use drop_last in Dataloader, it doesn't work. and reset the batchsize=1, when i=12936, errors occured.
a_real = a_real[0].to(device)
TypeError: 'NoneType' object is not subscriptable

**Comment by Simon4Yan** [comment]
Maybe you should check your data loader. You could check the data preparation in https://github.com/LynnHo/CycleGAN-Tensorflow-2/tree/v1. Or you could write your own data loader.

**Comment by zwzhang121** [comment]
thx. before running the spgan, i did not modify any codes, including the data loader. so, is there some bugs?

**Comment by Simon4Yan** [comment]
By the way, maybe you could check the length of "itertools.izip(a_loader, b_loader)". Also, the length of a_loader and b_loader.

I remember the training data size is 12,936, so the length of "itertools.izip(a_loader, b_loader)" should be 12936. In this case, the maximum of i is 12,935. 

You could check your dataset loader code step by step. Good luck!

**Comment by Simon4Yan** [comment]
First, I have released this code for about 11 months. You are the first one to find a "bug". I think you could check your code step by step. We didn't meet your issue, how can we find a "bug". I don't think the bug is a friendly word for someone who releases her/his codes (but the issue is welcome).
Moreover, I mean you need to check your data path preparation. You need to make sure you put images into the right path. Again, check the path structure in https://github.com/LynnHo/CycleGAN-Tensorflow-2/tree/v1.
Last, I have given you some possible ways to find out the issue.

**Comment by zwzhang121** [comment]
thanks for your detailed reply. 
I reclone the code and fix the errors, and apologizes.
